// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(MilesCarRentalDbContext))]
    [Migration("20240320222834_fourthMigration")]
    partial class fourthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GearBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Mazda",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "CX50",
                            NumberPlate = "NOE875",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Kia",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 1,
                            Model = "Seltos",
                            NumberPlate = "FJF811",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Renault",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Stepway",
                            NumberPlate = "UYQ55",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Chevrolet",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Captiva",
                            NumberPlate = "AAC717",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2018
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Renault",
                            Color = "Gris",
                            GearBox = "Automatico",
                            LocationId = 2,
                            Model = "Kwid",
                            NumberPlate = "ANO497",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2015
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Renault",
                            Color = "Verde",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "Duster",
                            NumberPlate = "YUT88",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Mazda",
                            Color = "Gris",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "3",
                            NumberPlate = "SGE835",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2016
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Kia",
                            Color = "Gris",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Seltos",
                            NumberPlate = "DHY1",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2024
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Mazda",
                            Color = "Azul",
                            GearBox = "Automatico",
                            LocationId = 6,
                            Model = "MX5",
                            NumberPlate = "OMP602",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Mazda",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "CX90",
                            NumberPlate = "MFK50",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Kia",
                            Color = "Gris",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Seltos",
                            NumberPlate = "WAZ493",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Mazda",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 1,
                            Model = "MX5",
                            NumberPlate = "POR457",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2017
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Mazda",
                            Color = "Gris",
                            GearBox = "Manual",
                            LocationId = 5,
                            Model = "CX30",
                            NumberPlate = "RTW767",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2016
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Renault",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 3,
                            Model = "Kwid",
                            NumberPlate = "SUP587",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2024
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Renault",
                            Color = "Negro",
                            GearBox = "Manual",
                            LocationId = 5,
                            Model = "Stepway",
                            NumberPlate = "MXR174",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2024
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Chevrolet",
                            Color = "Blanco",
                            GearBox = "Automatico",
                            LocationId = 4,
                            Model = "Captiva",
                            NumberPlate = "HVO761",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2017
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Mazda",
                            Color = "Negro",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "3",
                            NumberPlate = "WMY785",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2014
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Mazda",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "CX90",
                            NumberPlate = "USL352",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2020
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Mazda",
                            Color = "Negro",
                            GearBox = "Manual",
                            LocationId = 5,
                            Model = "CX90",
                            NumberPlate = "UPB829",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2016
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Mazda",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "CX90",
                            NumberPlate = "CML53",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2014
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Mazda",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "CX30",
                            NumberPlate = "LZJ864",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2022
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Chevrolet",
                            Color = "Blanco",
                            GearBox = "Automatico",
                            LocationId = 5,
                            Model = "Captiva",
                            NumberPlate = "QDD8",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2018
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Renault",
                            Color = "Gris",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Kwid",
                            NumberPlate = "LZE298",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2024
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Mazda",
                            Color = "Blanco",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "CX50",
                            NumberPlate = "GAG850",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2024
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Mazda",
                            Color = "Verde",
                            GearBox = "Automatico",
                            LocationId = 7,
                            Model = "CX50",
                            NumberPlate = "OXO79",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2020
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Mazda",
                            Color = "Amarillo",
                            GearBox = "Automatico",
                            LocationId = 4,
                            Model = "CX50",
                            NumberPlate = "HHU651",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2015
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Chevrolet",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Cruze",
                            NumberPlate = "OHI602",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2014
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Kia",
                            Color = "Azul",
                            GearBox = "Automatico",
                            LocationId = 5,
                            Model = "Sorento",
                            NumberPlate = "BLQ819",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2015
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Renault",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 5,
                            Model = "Stepway",
                            NumberPlate = "IKM38",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2018
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Renault",
                            Color = "Gris",
                            GearBox = "Manual",
                            LocationId = 1,
                            Model = "Stepway",
                            NumberPlate = "CIX522",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2022
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Mazda",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "CX50",
                            NumberPlate = "EVS289",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2017
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Mazda",
                            Color = "Verde",
                            GearBox = "Manual",
                            LocationId = 1,
                            Model = "CX90",
                            NumberPlate = "OAY436",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Chevrolet",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Cruze",
                            NumberPlate = "LZG965",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2022
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Chevrolet",
                            Color = "Gris",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Sail",
                            NumberPlate = "ZBM568",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2023
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Renault",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Stepway",
                            NumberPlate = "JXY470",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2014
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Chevrolet",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "Sail",
                            NumberPlate = "HTN235",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2023
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Chevrolet",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "Captiva",
                            NumberPlate = "MWW878",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Kia",
                            Color = "Negro",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Seltos",
                            NumberPlate = "QVT836",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2020
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Chevrolet",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 3,
                            Model = "Captiva",
                            NumberPlate = "ZBT673",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2022
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Chevrolet",
                            Color = "Verde",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "Cruze",
                            NumberPlate = "LUA444",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2022
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Renault",
                            Color = "Negro",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "Duster",
                            NumberPlate = "FND190",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2016
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Renault",
                            Color = "Café",
                            GearBox = "Automatico",
                            LocationId = 3,
                            Model = "Oroch",
                            NumberPlate = "HXC970",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2014
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Chevrolet",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 3,
                            Model = "Sail",
                            NumberPlate = "WNL967",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2017
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Chevrolet",
                            Color = "Negro",
                            GearBox = "Automatico",
                            LocationId = 4,
                            Model = "Spark",
                            NumberPlate = "YFZ27",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2017
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Kia",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "Seltos",
                            NumberPlate = "DGJ695",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2023
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Chevrolet",
                            Color = "Amarillo",
                            GearBox = "Automatico",
                            LocationId = 6,
                            Model = "Spark",
                            NumberPlate = "FSO302",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2024
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Mazda",
                            Color = "Blanco",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "CX90",
                            NumberPlate = "GRR715",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Kia",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "Sportage",
                            NumberPlate = "DRY956",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Kia",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 3,
                            Model = "Sorento",
                            NumberPlate = "MYE52",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2017
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Kia",
                            Color = "Gris",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Sorento",
                            NumberPlate = "HUG777",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 51,
                            Brand = "Renault",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 5,
                            Model = "Kwid",
                            NumberPlate = "AJY630",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 52,
                            Brand = "Renault",
                            Color = "Negro",
                            GearBox = "Automatico",
                            LocationId = 1,
                            Model = "Duster",
                            NumberPlate = "QXA527",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2020
                        },
                        new
                        {
                            Id = 53,
                            Brand = "Mazda",
                            Color = "Blanco",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "CX30",
                            NumberPlate = "EPK130",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2015
                        },
                        new
                        {
                            Id = 54,
                            Brand = "Chevrolet",
                            Color = "Azul",
                            GearBox = "Automatico",
                            LocationId = 6,
                            Model = "Spark",
                            NumberPlate = "ZRJ866",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2016
                        },
                        new
                        {
                            Id = 55,
                            Brand = "Kia",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "Sorento",
                            NumberPlate = "XEM939",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2020
                        },
                        new
                        {
                            Id = 56,
                            Brand = "Chevrolet",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 3,
                            Model = "Captiva",
                            NumberPlate = "IJM72",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2015
                        },
                        new
                        {
                            Id = 57,
                            Brand = "Kia",
                            Color = "Blanco",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Sorento",
                            NumberPlate = "NAD627",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2017
                        },
                        new
                        {
                            Id = 58,
                            Brand = "Chevrolet",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 1,
                            Model = "Captiva",
                            NumberPlate = "RWQ510",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 59,
                            Brand = "Chevrolet",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "Aveo",
                            NumberPlate = "GWD182",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2016
                        },
                        new
                        {
                            Id = 60,
                            Brand = "Kia",
                            Color = "Verde",
                            GearBox = "Automatico",
                            LocationId = 2,
                            Model = "Seltos",
                            NumberPlate = "BRN385",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 61,
                            Brand = "Kia",
                            Color = "Azul",
                            GearBox = "Automatico",
                            LocationId = 5,
                            Model = "Sorento",
                            NumberPlate = "HFO42",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 62,
                            Brand = "Renault",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "Duster",
                            NumberPlate = "ZDF894",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2018
                        },
                        new
                        {
                            Id = 63,
                            Brand = "Mazda",
                            Color = "Negro",
                            GearBox = "Automatico",
                            LocationId = 7,
                            Model = "CX50",
                            NumberPlate = "PYP943",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2020
                        },
                        new
                        {
                            Id = 64,
                            Brand = "Chevrolet",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 1,
                            Model = "Captiva",
                            NumberPlate = "RHU790",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2014
                        },
                        new
                        {
                            Id = 65,
                            Brand = "Renault",
                            Color = "Blanco",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Duster",
                            NumberPlate = "FMN829",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2014
                        },
                        new
                        {
                            Id = 66,
                            Brand = "Kia",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "Sorento",
                            NumberPlate = "QHS646",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 67,
                            Brand = "Renault",
                            Color = "Blanco",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "Stepway",
                            NumberPlate = "ALC736",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2024
                        },
                        new
                        {
                            Id = 68,
                            Brand = "Renault",
                            Color = "Café",
                            GearBox = "Automatico",
                            LocationId = 2,
                            Model = "Oroch",
                            NumberPlate = "EAA501",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 69,
                            Brand = "Renault",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Stepway",
                            NumberPlate = "HJF693",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2016
                        },
                        new
                        {
                            Id = 70,
                            Brand = "Mazda",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 1,
                            Model = "CX50",
                            NumberPlate = "NXS797",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 71,
                            Brand = "Mazda",
                            Color = "Negro",
                            GearBox = "Automatico",
                            LocationId = 4,
                            Model = "CX90",
                            NumberPlate = "QWA8",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2017
                        },
                        new
                        {
                            Id = 72,
                            Brand = "Renault",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 5,
                            Model = "Kwid",
                            NumberPlate = "BDF784",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2016
                        },
                        new
                        {
                            Id = 73,
                            Brand = "Chevrolet",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 6,
                            Model = "Cruze",
                            NumberPlate = "ATQ76",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 74,
                            Brand = "Mazda",
                            Color = "Verde",
                            GearBox = "Automatico",
                            LocationId = 4,
                            Model = "CX50",
                            NumberPlate = "VTD260",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 75,
                            Brand = "Mazda",
                            Color = "Gris",
                            GearBox = "Manual",
                            LocationId = 3,
                            Model = "3",
                            NumberPlate = "IZG917",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2021
                        },
                        new
                        {
                            Id = 76,
                            Brand = "Chevrolet",
                            Color = "Blanco",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Captiva",
                            NumberPlate = "DME308",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2024
                        },
                        new
                        {
                            Id = 77,
                            Brand = "Mazda",
                            Color = "Blanco",
                            GearBox = "Automatico",
                            LocationId = 3,
                            Model = "3",
                            NumberPlate = "VCQ146",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 78,
                            Brand = "Mazda",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "CX90",
                            NumberPlate = "FGP714",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2023
                        },
                        new
                        {
                            Id = 79,
                            Brand = "Renault",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 5,
                            Model = "Oroch",
                            NumberPlate = "PIS687",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2020
                        },
                        new
                        {
                            Id = 80,
                            Brand = "Chevrolet",
                            Color = "Verde",
                            GearBox = "Manual",
                            LocationId = 3,
                            Model = "Captiva",
                            NumberPlate = "EFV401",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 81,
                            Brand = "Chevrolet",
                            Color = "Café",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Aveo",
                            NumberPlate = "AIZ187",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2022
                        },
                        new
                        {
                            Id = 82,
                            Brand = "Renault",
                            Color = "Negro",
                            GearBox = "Manual",
                            LocationId = 1,
                            Model = "Duster",
                            NumberPlate = "PED984",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2015
                        },
                        new
                        {
                            Id = 83,
                            Brand = "Chevrolet",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "Spark",
                            NumberPlate = "TAG315",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2022
                        },
                        new
                        {
                            Id = 84,
                            Brand = "Kia",
                            Color = "Azul",
                            GearBox = "Manual",
                            LocationId = 3,
                            Model = "Sportage",
                            NumberPlate = "MTB676",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2018
                        },
                        new
                        {
                            Id = 85,
                            Brand = "Kia",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 4,
                            Model = "Sorento",
                            NumberPlate = "DUG929",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2024
                        },
                        new
                        {
                            Id = 86,
                            Brand = "Renault",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Kwid",
                            NumberPlate = "QUR869",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2022
                        },
                        new
                        {
                            Id = 87,
                            Brand = "Mazda",
                            Color = "Amarillo",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "CX30",
                            NumberPlate = "SYI867",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2016
                        },
                        new
                        {
                            Id = 88,
                            Brand = "Renault",
                            Color = "Blanco",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Oroch",
                            NumberPlate = "JHY656",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2019
                        },
                        new
                        {
                            Id = 89,
                            Brand = "Chevrolet",
                            Color = "Negro",
                            GearBox = "Manual",
                            LocationId = 2,
                            Model = "Aveo",
                            NumberPlate = "ZFM365",
                            SeatNumber = 4,
                            Status = false,
                            Year = 2022
                        },
                        new
                        {
                            Id = 90,
                            Brand = "Mazda",
                            Color = "Verde",
                            GearBox = "Manual",
                            LocationId = 5,
                            Model = "MX5",
                            NumberPlate = "EWX251",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2023
                        },
                        new
                        {
                            Id = 91,
                            Brand = "Chevrolet",
                            Color = "Rojo",
                            GearBox = "Manual",
                            LocationId = 5,
                            Model = "Cruze",
                            NumberPlate = "FUT943",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2018
                        },
                        new
                        {
                            Id = 92,
                            Brand = "Mazda",
                            Color = "Verde",
                            GearBox = "Manual",
                            LocationId = 7,
                            Model = "MX5",
                            NumberPlate = "VKQ362",
                            SeatNumber = 5,
                            Status = false,
                            Year = 2014
                        });
                });

            modelBuilder.Entity("Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Carrera 23 # 45",
                            City = "Bogota",
                            NameLocation = "Chico Norte"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Carrera 12 # 45",
                            City = "Bogota",
                            NameLocation = "Bosa"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Carrera 34 # 45",
                            City = "Bogota",
                            NameLocation = "Usme"
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Carrera 55 # 32",
                            City = "Medellin",
                            NameLocation = "Provenza"
                        },
                        new
                        {
                            Id = 5,
                            Adress = "Carrera 12 # 32",
                            City = "Medellin",
                            NameLocation = "Poblado"
                        },
                        new
                        {
                            Id = 6,
                            Adress = "Av Murillo # 15",
                            City = "Barranquilla",
                            NameLocation = "Barrio Abajo"
                        },
                        new
                        {
                            Id = 7,
                            Adress = "Carrera 4 # 40",
                            City = "Barranquilla",
                            NameLocation = "Malecon"
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentId = 6788729,
                            Name = " Hugo García"
                        },
                        new
                        {
                            Id = 2,
                            DocumentId = 65772969,
                            Name = " Martín Rodríguez"
                        },
                        new
                        {
                            Id = 3,
                            DocumentId = 38745615,
                            Name = " Lucas González"
                        },
                        new
                        {
                            Id = 4,
                            DocumentId = 76848338,
                            Name = " Mateo Fernández"
                        },
                        new
                        {
                            Id = 5,
                            DocumentId = 56040483,
                            Name = " Leo López"
                        },
                        new
                        {
                            Id = 6,
                            DocumentId = 16904163,
                            Name = " Daniel Martínez"
                        },
                        new
                        {
                            Id = 7,
                            DocumentId = 16426418,
                            Name = " Alejandro Sánchez"
                        },
                        new
                        {
                            Id = 8,
                            DocumentId = 14780125,
                            Name = " Pablo Pérez"
                        },
                        new
                        {
                            Id = 9,
                            DocumentId = 43625518,
                            Name = " Manuel Gómez"
                        },
                        new
                        {
                            Id = 10,
                            DocumentId = 23265025,
                            Name = " Álvaro Martín"
                        },
                        new
                        {
                            Id = 11,
                            DocumentId = 48842146,
                            Name = " Adrián Jimenez"
                        },
                        new
                        {
                            Id = 12,
                            DocumentId = 95791823,
                            Name = " David Hernández"
                        },
                        new
                        {
                            Id = 13,
                            DocumentId = 65087482,
                            Name = " Mario Ruiz"
                        },
                        new
                        {
                            Id = 14,
                            DocumentId = 4191223,
                            Name = " Enzo Díaz"
                        },
                        new
                        {
                            Id = 15,
                            DocumentId = 33925090,
                            Name = " Diego Moreno"
                        },
                        new
                        {
                            Id = 16,
                            DocumentId = 14120076,
                            Name = " Marcos Muñoz"
                        },
                        new
                        {
                            Id = 17,
                            DocumentId = 49253492,
                            Name = " Izan Álvarez"
                        },
                        new
                        {
                            Id = 18,
                            DocumentId = 52519468,
                            Name = " Javier Romero"
                        },
                        new
                        {
                            Id = 19,
                            DocumentId = 16057111,
                            Name = " Marco Gutiérrez"
                        },
                        new
                        {
                            Id = 20,
                            DocumentId = 91200892,
                            Name = " Álex Alonso"
                        },
                        new
                        {
                            Id = 21,
                            DocumentId = 43707990,
                            Name = " Bruno Navarro"
                        },
                        new
                        {
                            Id = 22,
                            DocumentId = 24476816,
                            Name = " Oliver Torres"
                        });
                });

            modelBuilder.Entity("Domain.Car", b =>
                {
                    b.HasOne("Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Location");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
